server:
  port : 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password : root
    driver : com.mysql.jdbc.Driver

  jpa :
    hibernate:
      ddl-auto : update
    show-sql : true